config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  validates :title, presence: true
  validates :body, presence: true,
                      length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @users = User.all
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end
  
  def edit
    if @post.user != current_user
      redirect_to posts_path, notice: "連絡先を登録しました"
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to @post.user, notice: "投稿を削除しました。"
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end

    def find_post
      @post = Post.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_params, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show

  end

  def edit
    if @user != current_user
      redirect_to current_user
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :profile, :profile_image)
    end

    def find_params
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<%= render 'shared/flash_messages' %>

    <% if user_signed_in? %>
      <%= render template: "posts/index" %>
    <% else %>
      <div class="container">
        <div class="jumbotron  mt-4 text-center">
          <%= link_to image_tag("railsPosts.png", alt: "logo", class: 'img-fluid'), root_path %>
        </div>
      </div>


    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPosts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>

    
    
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<section class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container py-3 d-flex">
    <h2 class="text-light">
    投稿編集
    </h2>
  </div>
</section>

<div class="container-login">
  <section>
    <%= form_for @post do |f| %>

      <div class="form-group">
        <%= f.label :tilte, 'タイトル' %>  
        <%= f.text_field :title, autofocus: true, autocomplete: 'title', class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :body, '本文' %>
        <%= f.text_area :body, autofocus: true, autocomplete: 'body', class: 'form-control' %>
      </div>

      <div class="form-group">
          <%= f.label :image, "画像" %>
          <%= f.attachment_field :image, class: "form-control" %>
      </div>

          <%= f.submit "更新", class: 'btn btn-primary btn-block mt-5' %>
    <% end %>
  </section>
</div>

app/views/posts/index.html.erb
<section class="navbar-expand-lg navbar-dark bg-success">
  <div class="d-flex py-3">
    <%= link_to root_path, class: 'nav-link' do %>
      <h1 class='text-light'>投稿一覧</h1>
    <% end %>
      <ul class="nav ml-auto">
        <li class="nav-item align-self-center mr-0.5">
          <h4>
            <%= link_to '新規投稿', new_post_path, class: 'nav-link text-light' %>
          </h4>
        </li>
        <li class="nav-item align-self-center mr-0.5">
          <h4>
            <%= link_to 'ユーザー一覧', users_path, class: 'nav-link text-light' %>
          </h4>
        </li>
        <li class="nav-item align-self-center mr-3">
          <h4>
            <%= link_to 'マイページ', user_path(current_user), class: 'nav-link text-light' %>
          </h4>
        </li>

      </ul>
  </div>
</section>

<section class=''>
  <div class="container">
    <div class="row mb-5">
      <% @posts.each do |post| %>
        <div class="col-md-3 bg-white mt-5 ">
          <%= link_to post do %>
            <div class="pt-3">
              <%= attachment_image_tag post, :image, class: 'img-fluid image_tag'%>
              <p class="mt-2"><%= post.title %><p>
              <p><%= post.user.username %></p>
              <p><%= l post.updated_at, format: :long %></p>
            </div>
          <% end %>
        </div>
      <%end %> 
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-alert alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= @post.errors.count %>つのエラーがあります。
    <ul class=''>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message  %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container py-3 d-flex">
    <h2 class="text-light">
    新規投稿
    </h2>
  </div>
</section>

<div class="container-login">
  <section>
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :title, "タイトル" %>
        <%= f.text_field :title, autofocus: true, autocomplete: 'tilte', class: 'form-control' %>
      </div>

      <div class="from-group mt-3">
      <%= f.label :body, "本文" %>
      <%= f.text_area :body, autofocus: true, autocomplete: 'body', class: 'form-control' %>
      </div>

      <div class="from-group mt-3">
        <%= f.label :image, "イメージ" %>
        <%= f.attachment_field :image, class: 'form-control' %>
      </div>

      <%= f.submit '投稿する', class: 'btn btn-success btn-block mt-5' %>

      <% end %>
  </section>
</div>

app/views/posts/show.html.erb
<section class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container py-3 d-flex">
    <%= link_to @post.user, class: 'nav-link text-light' do %>
      <h1>
        <%= @post.user.username %>さん<span class= 'h4 ml-3'>のページへ</span>
      </h1>
    <% end %>
    <% if @post.user.id == current_user.id %>
      <ul class='nav'>
        <li class='nav-item'>
          <h5 class= 'ml-auto' >
            <%= link_to '編集', [:edit, @post], class: 'nav-link text-light' %>
          </h5>
        </li>
      </ul>
    <% end %>
  </div>
</section>

<section class='mt-5'>
  <div class="container">
    <div class="row">

      <div class="col-lg-4 offset-2 align-self-baseline">
        <%= attachment_image_tag @post, :image, class: "img-fluid"  %>
      </div>

      <div class="col-lg-4 pt-3 pt-lg-0 content">
        <h3><%= @post.title %></h3>
        <p><%= simple_format @post.body %></p>      
      </div>      
    </div>
  </div>
</section>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to "RailsPosts", root_path, class: 'navbar-brand nav-link' %>


      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <ul class="nav">
            <li class="nav-item active">
              <%= link_to '投稿一覧', posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          </ul>
        <% else %>

          <button class="navbar-toggler" type="button" data-toggle="collapse"     data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"    aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div id="navbarNav" class="collapse navbar-collapse">
            <li class="nav-item active">
              <a class="nav-link" href="users/sign_up">新規登録 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/users/edit.html.erb
<section class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container py-3 d-flex">
    <h2 class="text-light">
    プロフィール編集
    </h2>
    <h5 class="ml-auto">
    <%= link_to 'パスワード編集', edit_user_registration_path, class: 'text-light text-decoration-none' %>
    </h5>
  </div>
</section>

<div class="container-login">
<section>
  <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label :username %>  
      <%= f.text_field :username, autofocus: true, autocomplete: 'username', class: 'form-control' %>
    </div>
    
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.label :profile, "プロフィール" %>
      <%= f.text_area :profile, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :profile_image, "プロフィール画像" %>
        <%= f.attachment_field :profile_image, class: "form-control" %>
    </div>

        <%= f.submit "更新", class: 'btn btn-primary btn-block mt-5' %>
  <% end %>
</section>
</div>

app/views/users/index.html.erb
<section class="navbar-expand-lg navbar-dark bg-success">
  <div class="d-flex py-3">
    <%= link_to root_path, class: 'nav-link' do %>
      <h1 class='text-light'>ユーザー一覧</h1>
    <% end %>
      <ul class="nav ml-auto">
        <li class="nav-item align-self-center mr-3">
          <h3>
            <%= link_to '投稿一覧', posts_path, class: 'nav-link text-light' %>
          </h3>
        </li>
      </ul>
  </div>
</section>

<section class='mt-4'>
  <div class="container">
    <div class="row">
            <% @users.each do |user| %>
        <div class="col-md-3 bg-white mt-5">
          <%= link_to user, class: 'text-decoration-none' do %>
            <div class="pt-3">
              <%= attachment_image_tag user, :profile_image, fallback: "no-image.png", class: 'img-fluid image_tag'%>
              <p class='mt-3'><%= user.username %></p>
              <p><%= l user.updated_at, format: :long %></p>
            </div>
            <div class="posts-count">
              <p>
                投稿数： <%= user.posts.count %>
              </p>
            </div>
          <% end %>
        </div>
      <%end %> 
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container py-3 d-flex">
    <h1 class="text-light">
      <%= @user.username %>さん
    </h1>
    <% if @user.id == current_user.id %>
    <h4 class= 'text-light mr-auto pl-3 '>
      <%= @user.email %>
    </h4>
      <ul class="nav">
        <li class="nav-item">
          <h5 class= 'ml-auto' >
            <%= link_to '新規投稿', new_post_path, class: 'text-light text-decoration-none' %>
            <%= link_to '編集', [:edit, @user], class: 'text-light text-decoration-none ml-2' %>
          </h5>
        </li>
        <li class="nav-item"></li>
      </ul>
    <% end %>
  </div>
</section>


<div class="container mt-5">
  <section>
    <div class="row">
      <div class="col-lg-3 offset-2 align-self-baseline">
        <div class="">
          <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: 'img-fluid' %>
        </div>
      </div>

      <div class="col-lg-5 pt-3 pt-lg-0 content">
        <%= simple_format @user.profile %>
      </div>      
    </div>
  </section>

  <section class='mt-5 '>
    <div class="container" >
      <div class="row">
        <% @user.posts.each do |post| %>
          <div class="col-md-3 bg-white my-3">
            <div class="pt-3">
              <%= link_to post, class: 'text-decoration-none' do %>
                <%= attachment_image_tag post, :image, fallback: "no-image.png", class: 'img-fluid image_tag'%>
            </div>
              <% end %>
            <div class="text-center pb-3">
              <div class="mt-3">
                <%= link_to '詳細を見る', post %>
              </div>
              <div class="">
                <% if @user.id == current_user.id %>
                  <%= link_to '編集する', [:edit, post], class: '' %> <br>
                  <%= link_to '削除する', post_path(post), method: :delete, data: {confirm: "削除しますか？"} %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>    
  </section>

</div>